// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB-j36Zqu3Vqq_YkwlPv1gfx6CExbegJc',
    appId: '1:281211190180:ios:78c42a6ad43b61c0cb9f31',
    messagingSenderId: '281211190180',
    projectId: 'legal-sathi-2025-d4124',
    storageBucket: 'legal-sathi-2025-d4124.firebasestorage.app',
    iosBundleId: 'com.nyaymitra.nyayMitraApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVIU1825pcfO1xpfJq2QNKNptyJkNPE9g',
    appId: '1:281211190180:android:5dc4911ee90bd907cb9f31',
    messagingSenderId: '281211190180',
    projectId: 'legal-sathi-2025-d4124',
    storageBucket: 'legal-sathi-2025-d4124.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTElzRe535zcbpUiT9lzLWgioZgQYCIU0',
    appId: '1:301563122094:web:a5635aa0d64c416765b83f',
    messagingSenderId: '301563122094',
    projectId: 'lexani-5df0d',
    authDomain: 'lexani-5df0d.firebaseapp.com',
    storageBucket: 'lexani-5df0d.firebasestorage.app',
    measurementId: 'G-281GY583RD',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTElzRe535zcbpUiT9lzLWgioZgQYCIU0',
    appId: '1:301563122094:web:a5635aa0d64c416765b83f',
    messagingSenderId: '301563122094',
    projectId: 'lexani-5df0d',
    authDomain: 'lexani-5df0d.firebaseapp.com',
    storageBucket: 'lexani-5df0d.firebasestorage.app',
    measurementId: 'G-281GY583RD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB-j36Zqu3Vqq_YkwlPv1gfx6CExbegJc',
    appId: '1:281211190180:ios:78c42a6ad43b61c0cb9f31',
    messagingSenderId: '281211190180',
    projectId: 'legal-sathi-2025-d4124',
    storageBucket: 'legal-sathi-2025-d4124.firebasestorage.app',
    iosBundleId: 'com.nyaymitra.nyayMitraApp',
  );

}